### ISSUE TITLE
Build and performance issues

### ISSUE THREAD

**Issue by rayrapetyan** [KjellKod/g3sinks#11] opened 2015-09-25 16:07 UTC
Hi, just want to share few observations (sorry for a long code listings, it was easier for me than forking\pulling).

# Build process.

### Had minor issues with unit-tests. So basically made them optional in test/Test.cmake:
```
# =====================================================
#  Public Domain: Inspired by github.com/KjellKod/g3log/CMakeLists.cmake
#  2015, April 30, @author Kjell.Hedstrom
# =====================================================

option (ADD_LOGROTATE_UNIT_TEST "logrotate unit tests" OFF)

IF (ADD_LOGROTATE_UNIT_TEST)

    set(GTEST_DIR ${DIR_3RDPARTY}/gtest-1.7.0)
    set(GTEST_INCLUDE_DIRECTORIES ${GTEST_DIR}/include ${GTEST_DIR} ${GTEST_DIR}/src)
    MESSAGE( "Attempt to build gtest. gtest directory: " ${GTEST_DIR})
    include_directories(${GTEST_INCLUDE_DIRECTORIES})
    add_library(gtest_170_lib ${GTEST_DIR}/src/gtest-all.cc)
    set_target_properties(gtest_170_lib PROPERTIES COMPILE_DEFINITIONS "GTEST_HAS_RTTI=0")
    enable_testing(true)
    include_directories(test)
    file(GLOB TEST_SRC_FILES "test/*.cpp" "test/*.h" "test/*.hpp")
    set(TestRunner UnitTestRunner)

    # build the unit tests   
    add_executable(${TestRunner} ${DIR_3RDPARTY}/test_main.cpp ${TEST_SRC_FILES} )
    set_target_properties(${TestRunner} PROPERTIES COMPILE_DEFINITIONS "GTEST_HAS_TR1_TUPLE=0")
    set_target_properties(${TestRunner} PROPERTIES COMPILE_DEFINITIONS "GTEST_HAS_RTTI=0")
    set_target_properties(${TestRunner} PROPERTIES COMPILE_FLAGS "-isystem -pthread ")
    target_link_libraries(${TestRunner} ${LIBRARY_TO_BUILD} ${G3LOG} gtest_170_lib -lstdc++ ${TCMALLOC}  ${PLATFORM_LINK_LIBRIES} -Wl,-rpath,. -Wl,-rpath,${G3_LIBRARY_PATH}  -Wl,-rpath,${G3_LIBRARY_PATH}/../lib64 )

    MESSAGE("library to build ${LIBRARY_TO_BUILD}")

ELSE() 
  MESSAGE("-DADD_LOGROTATE_UNIT_TEST=OFF") 
ENDIF (ADD_LOGROTATE_UNIT_TEST)

```

### CmakeLists.txt. Changed to static compilation, wrapped boost libs handling, added clang support (copied from g3log):
```
# =====================================================
#  Public Domain: Inspired by github.com/KjellKod/g3log/CMakeLists.cmake
#  2015, April 30, @author Kjell.Hedstrom
# =====================================================

CMAKE_MINIMUM_REQUIRED (VERSION 2.8)
ENABLE_LANGUAGE(CXX)
SET(CMAKE_BUILD_TYPE Release)

PROJECT (LogRotate)
SET(PROJECT_SRC ${LogRotate_SOURCE_DIR}/src)
SET(DIR_UNIT_TEST ${LogRotate_SOURCE_DIR}/test)
SET(DIR_3RDPARTY ${LogRotate_SOURCE_DIR}/../3rdparty)


MESSAGE(" PROJECT_SRC = : ${PROJECT_SRC}")
INCLUDE_DIRECTORIES(${PROJECT_SRC})
SET(ACTIVE_CPP0xx_DIR "Release")

# Load PATHS
INCLUDE (${LogRotate_SOURCE_DIR}/Options.cmake)
INCLUDE_DIRECTORIES(${G3_HEADER_PATH})

#Find all libraries

find_package(Boost COMPONENTS filesystem system regex REQUIRED)
include_directories(${Boost_INCLUDE_DIRS})

find_library(G3LOG g3logger PATHS ${G3_LIBRARY_PATH})

IF ("${CMAKE_CXX_COMPILER_ID}" MATCHES ".*Clang")
   MESSAGE("")
   MESSAGE("cmake for Clang ")
   SET(CMAKE_CXX_FLAGS "-Wall -std=c++11 -stdlib=libc++ -Wunused -D_GLIBCXX_USE_NANOSLEEP")
   IF (${CMAKE_SYSTEM} MATCHES "FreeBSD-([0-9]*)\\.(.*)")
       IF (${CMAKE_MATCH_1} GREATER 9)
           set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
           set(PLATFORM_LINK_LIBRIES execinfo)
       ENDIF()
   ELSEIF (APPLE)
       set(PLATFORM_LINK_LIBRIES c++abi)
   ELSE()
       set(PLATFORM_LINK_LIBRIES rt c++abi)
   ENDIF()

ELSEIF ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
   MESSAGE("")
   MESSAGE("cmake for GCC ")
   SET(PLATFORM_LINK_LIBRIES rt)
   SET(CMAKE_CXX_FLAGS "-Wall -rdynamic -Wunused -std=c++11 -pthread -D_GLIBCXX_USE_NANOSLEEP")
ENDIF()


# GENERIC STEPS
FILE(GLOB SRC_FILES ${PROJECT_SRC}/*.h ${PROJECT_SRC}/*.h ${PROJECT_SRC}/*.ipp ${PROJECT_SRC}/*.cpp) 


# Setup Library name
SET(LIBRARY_TO_BUILD g3logrotate)

# Build the library
INCLUDE_DIRECTORIES(${PROJECT_SRC})
ADD_LIBRARY(${LIBRARY_TO_BUILD} ${SRC_FILES})
SET(${LIBRARY_TO_BUILD}_VERSION_STRING)
SET_TARGET_PROPERTIES(${LIBRARY_TO_BUILD} PROPERTIES LINKER_LANGUAGE CXX)
TARGET_LINK_LIBRARIES(${LIBRARY_TO_BUILD} ${TCMALLOC} ${Boost_LIBRARIES} z ${G3LOG})



# Setup unit tests
INCLUDE (${LogRotate_SOURCE_DIR}/test/Test.cmake)

```

### Options.cmake:
```
# =====================================================
#  Public Domain: Inspired by github.com/KjellKod/g3log/Options.cmake
#  2015, August 17, @author Kjell.Hedstrom
# =====================================================


# Override the default path for g3log library
#example1:  cmake -DG3_LIBRARY_PATH="/usr/local/probe/lib"
#example2:  cmake -DG3_LIBRARY_PATH="/home/kjell/Github/g3log/build"
#http://stackoverflow.com/questions/12984181/specifying-include-directories-on-the-cmake-command-line

#
#set(YOURLIB_INCLUDE_DIR "" CACHE FILEPATH "Path to yourlib includes")
#
#if(NOT YOURLIB_INCLUDE_DIR/header.h)
#  message(SEND_ERROR "Can't find header.h in ${YOURLIB_INCLUDE_DIR})
#endif()
#
#include_directories(${YOURLIB_INCLUDE_DIR})


SET(G3_LIBRARY_PATH "" CACHE FILEPATH "Path to g3log libraries")
IF(EXISTS "${G3_LIBRARY_PATH}/libg3logger.a")
   MESSAGE("SUCCESS lib")
ELSE()
  MESSAGE(SEND_ERROR "Can't find g3logger library file in G3_LIBRARY_PATH/libg3logger.a:' ${G3_LIBRARY_PATH}'. Please set it with '-DG3_LIBRARY_PATH'")
ENDIF()



SET(G3_HEADER_PATHa "" CACHE FILEPATH "Path to g3log headers")
IF(EXISTS ${G3_HEADER_PATH}/g3log/g3log.hpp)
   MESSAGE("SUCCESS path")
ELSE()
  MESSAGE(FATAL_ERROR "Can't find g3log.hpp at G3_HEADER_PATH/g3log/g3log.hpp, i.e. '${G3_HEADER_PATH}/g3log/g3log.hpp'. Please set it with '-DG3_HEADER_PATH'")
ENDIF()



#option (USE_G3_LIBRARY_PATH
#       "Find g3log libraries by this path instead of default" OFF)
#SET(G3_LIBRARY_PATH_DEFAULT "/usr/local/lib/")
#IF (${USE_G3PATH_LIBRARY} )
#   SET(G3_LIBRARY_PATH ${USE_G3_LIBRARY_PATH})
#ELSE()
#   SET(G3_LIBRARY_PATH ${G3_LIBRARY_PATH_DEFAULT})
#ENDIF()

#MESSAGE("G3_LIBRARY_PATH = " ${G3_LIBRARY_PATH})
#MESSAGE("You can change it with  cmake -DUSE_G3_LIBRARY_PATH=path_to_libraries (i.e. something like /usr/local/lib)")



# Override the default path for looking up g3log headers 
#example1:  cmake -DUSE_G3_HEADER_PATH="/usr/local/probe/include/"
#example2:  cmake -DUSE_G3_HEADER_PATH="/home/kjell/Github/g3log/src"
#option (USE_G3_HEADER_PATH
#       "Find g3log headers by this path instead of default" OFF)
#SET(G3_HEADER_PATH_DEFAULT "/usr/local/include/")
#
#IF (${USE_G3_HEADER_PATH} ) 
#   SET(G3_HEADER_PATH ${USE_G3_HEADER_PATH})
#ELSE()
#   SET(G3_HEADER_PATH ${G3_HEADER_PATH_DEFAULT})
#ENDIF()

#MESSAGE("G3_HEADER_PATH = " ${G3_HEADER_PATH})
#MESSAGE("You can change it with  cmake -DUSE_G3_HEADER_PATH=path_to_headers (i.e. something like /usr/local/include)")

```

# Performance issue.
First I thought there is a memleak somewhere, because even on a moderate load amount of memory constantly increased. Then using a valgrind found a place producing huge delays (actually two places):

- Using seekp in rotateLog (which is triggered on every fileWrite);
- Using "flush" in fileWrite;

So decided to drop "flush" and replace "seekp" strategy with a variable (cur_log_size). The resulting code of LogRotateHelper.ipp is below:
```
/** ==========================================================================
* 2011 by KjellKod.cc, modified by Vrecan in https://bitbucket.org/vrecan/g2log-dev
* 2015, adopted by KjellKod for g3log at:https://github.com/KjellKod/g3sinks
*
* This code is PUBLIC DOMAIN to use at your own risk and comes
* with no warranties. This code is yours to share, use and modify with no
* strings attached and no restrictions or obligations.
* ============================================================================*
* PUBLIC DOMAIN and Not copywrited. First published at KjellKod.cc
* ********************************************* */

#pragma once

#include <cstdio>
#include <string>
#include <memory>
#include <fstream>
#include <algorithm>
#include <future>
#include <cassert>
#include <chrono>
#include <g3log/time.hpp>
#include <zlib.h>
#include <boost/filesystem.hpp>
#include <boost/regex.hpp>
#include <map>
#include <vector>
#include <ctime>
#include <iostream>


namespace {
    using  steady_time_point = std::chrono::time_point<std::chrono::steady_clock>;

    static const std::string file_name_time_formatted = "%Y%m%d-%H%M%S";

    // check for filename validity -  filename should not be part of PATH
    bool isValidFilename(const std::string& prefix_filename) {
        std::string illegal_characters("/,|<>:#$%{}()[]\'\"^!?+* ");
        size_t pos = prefix_filename.find_first_of(illegal_characters, 0);
        if (pos != std::string::npos) {
            std::cerr << "Illegal character [" << prefix_filename.at(pos) << "] in logname prefix: " << "[" << prefix_filename << "]" << std::endl;
            return false;
        } else if (prefix_filename.empty()) {
            std::cerr << "Empty filename prefix is not allowed" << std::endl;
            return false;
        }

        return true;
    }
/// @return a corrected prefix, if needed,
/// illegal characters are removed from @param prefix input
    std::string prefixSanityFix(std::string prefix) {
        prefix.erase(std::remove_if(prefix.begin(), prefix.end(), ::isspace), prefix.end());
        prefix.erase(std::remove(prefix.begin(), prefix.end(), '/'), prefix.end()); // '/'
        prefix.erase(std::remove(prefix.begin(), prefix.end(), '\\'), prefix.end()); // '\\'
        prefix.erase(std::remove(prefix.begin(), prefix.end(), '.'), prefix.end()); // '.'
        if (!isValidFilename(prefix)) {
            return "";
        }
        return prefix;
    }

/// @return the file header
    std::string header() {
        std::ostringstream ss_entry;
        //  Day Month Date Time Year: is written as "%a %b %d %H:%M:%S %Y" and formatted output as : Wed Sep 19 08:28:16 2012
        ss_entry << "\ng3log: created log file at: " << g3::localtime_formatted(g3::systemtime_now(), "%a %b %d %H:%M:%S %Y") << "\n";
        return ss_entry.str();
    }

/// @return result as time from the file name
    bool getDateFromFileName(const std::string& app_name, const std::string& file_name, long& result) {
        if (file_name.find(app_name) != std::string::npos) {
            std::string suffix = file_name.substr(app_name.size());
            if (suffix.empty()) {
                //this is the main log file
                return false;
            }
            boost::regex date_regex("\\.(\\d{4}-\\d{2}-\\d{2}-\\d{2}-\\d{2}-\\d{2})\\.gz");
            boost::smatch date_match;
            if (boost::regex_match(suffix, date_match, date_regex)) {
                if (date_match.size() == 2) {
                    std::string date = date_match[1].str();
                    struct tm tm;
                    time_t t;
                    if (strptime(date.c_str(), "%Y-%m-%d-%H-%M-%S", &tm) == NULL) {
                        return false;
                    }
                    t = mktime(&tm);
                    if (t == -1) {
                        return false;
                    }
                    result = (long) t;
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * Loop through the files in the folder
     * @param dir
     * @param file_name
     */
    void expireArchives(const std::string dir, const std::string& app_name, unsigned long max_log_count) {
        std::map<long, std::string> files;

        boost::filesystem::path dir_path(dir);
        if (!boost::filesystem::exists(dir_path)) return;
        boost::filesystem::directory_iterator end_itr;
        for (boost::filesystem::directory_iterator itr(dir_path);
                itr != end_itr;
                ++itr) {
            std::string current_file(itr->path().filename().c_str());
            long time;
            if (getDateFromFileName(app_name, current_file, time)) {
                files.insert(std::pair<long, std::string > (time, current_file));
            }
        }
        //delete old logs.
        int logs_to_delete = files.size() - max_log_count;
        if (logs_to_delete > 0) {

            for (std::map<long, std::string>::iterator it = files.begin(); it != files.end(); ++it) {
                if (logs_to_delete <= 0) {
                    break;
                }

                std::stringstream ss;
                ss << dir.c_str() << it->second.c_str();
                remove(ss.str().c_str());
                --logs_to_delete;
            }
        }
    }


/// create the file name
    std::string createLogFileName(const std::string& verified_prefix) {
        std::stringstream oss_name;
        oss_name << verified_prefix << ".log";
        return oss_name.str();
    }


/// @return true if @param complete_file_with_path could be opened
/// @param outstream is the file stream
    bool openLogFile(const std::string& complete_file_with_path, std::ofstream& outstream) {
        std::ios_base::openmode mode = std::ios_base::out; // for clarity: it's really overkill since it's an ofstream
        mode |= std::ios_base::app;
        outstream.open(complete_file_with_path, mode);
        if (!outstream.is_open()) {
            std::ostringstream ss_error;
            ss_error << "FILE ERROR:  could not open log file:[" << complete_file_with_path << "]";
            ss_error << "\n\t\t std::ios_base state = " << outstream.rdstate();
            std::cerr << ss_error.str().c_str() << std::endl;
            outstream.close();
            return false;
        }
        return true;
    }

/// create the file
    std::unique_ptr<std::ofstream> createLogFile(const std::string& file_with_full_path) {
        std::unique_ptr<std::ofstream> out(new std::ofstream);
        std::ofstream& stream(*(out.get()));
        bool success_with_open_file = openLogFile(file_with_full_path, stream);
        if (false == success_with_open_file) {
            out.release();
        }
        return out;
    }

} // anonymous


/** The Real McCoy Background worker, while g3::LogWorker gives the
 * asynchronous API to put job in the background the LogRotateHelper
 * does the actual background thread work */
struct LogRotateHelper {
    LogRotateHelper& operator=(const LogRotateHelper&) = delete;
    LogRotateHelper(const LogRotateHelper& other) = delete;
    LogRotateHelper(const std::string& log_prefix, const std::string& log_directory);
    ~LogRotateHelper();

    void setMaxArchiveLogCount(int size);
    void setMaxLogSize(int size);
    void fileWrite(std::string message);
    std::string changeLogFile(const std::string& directory, const std::string& new_name = "");
    std::string logFileName();
    bool archiveLog();


    void addLogFileHeader();
    bool rotateLog();
    bool createCompressedFile(std::string file_name, std::string gzip_file_name);
    std::ofstream& filestream() {
        return *(outptr_.get());
    }

    std::string log_file_with_path_;
    std::string log_directory_;
    std::string log_prefix_backup_;
    std::unique_ptr<std::ofstream> outptr_;
    steady_time_point steady_start_time_;
    int max_log_size_;
    int max_archive_log_count_;
    int cur_log_size_;




};

LogRotateHelper::LogRotateHelper(const std::string& log_prefix, const std::string& log_directory)
    : log_file_with_path_(log_directory)
    , log_directory_(log_directory)
    , log_prefix_backup_(log_prefix)
    , outptr_(new std::ofstream)
    , steady_start_time_(std::chrono::steady_clock::now()) { // TODO: ha en timer function steadyTimer som har koll pÃ¥ start
    log_prefix_backup_ = prefixSanityFix(log_prefix);
    max_log_size_ = 524288000;
    max_archive_log_count_ = 10;    
    if (!isValidFilename(log_prefix_backup_)) {
        std::cerr << "g3log: forced abort due to illegal log prefix [" << log_prefix << "]" << std::endl;
        abort();
    }

    std::string file_name = createLogFileName(log_prefix_backup_);
    log_file_with_path_ = log_directory + file_name;
    outptr_ = createLogFile(log_file_with_path_);
    assert((nullptr != outptr_) && "cannot open log file at startup");
    addLogFileHeader();
    
    std::ofstream& is(filestream());
    is.seekp(0, std::ios::end);
    cur_log_size_ = is.tellp();
    is.seekp(0, std::ios::beg);
}

/**
 * Max number of archived logs to keep.
 * @param max_size
 */
void LogRotateHelper::setMaxArchiveLogCount(int max_size) {
    max_archive_log_count_ = max_size;
}

/**
 * Set the max file size in bytes.
 * @param max_size
 */
void LogRotateHelper::setMaxLogSize(int max_size) {
    max_log_size_ = max_size;
}

LogRotateHelper::~LogRotateHelper() {

    std::ostringstream ss_exit;
    ss_exit << "\ng3log file shutdown at: " << g3::localtime_formatted(g3::systemtime_now(), g3::internal::time_formatted) << "\n\n";
    filestream() << ss_exit.str() << std::flush;
}

void LogRotateHelper::fileWrite(std::string message) {
    rotateLog();
    std::ofstream& out(filestream());
    out << message;// << std::flush;
    cur_log_size_ += message.size();
}

std::string LogRotateHelper::changeLogFile(const std::string& directory, const std::string& new_name) {
    std::string file_name = new_name;
    if (file_name.empty()) {
       // std::cout << "no filename" << std::endl;
       file_name = createLogFileName(log_prefix_backup_);
    }


    std::string prospect_log = directory + file_name;
    std::unique_ptr<std::ofstream> log_stream = createLogFile(prospect_log);
    if (nullptr == log_stream) {
        fileWrite("Unable to change log file. Illegal filename or busy? Unsuccessful log name was:" + prospect_log);
        return ""; // no success
    }
    addLogFileHeader();

    std::ofstream& is(filestream());
    is.seekp(0, std::ios::end);
    cur_log_size_ = is.tellp();
    is.seekp(0, std::ios::beg);

    std::string old_log = log_file_with_path_;
    log_file_with_path_ = prospect_log;
    outptr_ = std::move(log_stream);
    log_directory_ = directory;
    return log_file_with_path_;
}

/**
 * Rotate the logs once they have exceeded our set size.
 * @return
 */
bool LogRotateHelper::rotateLog() {
    std::ofstream& is(filestream());
    if (is.is_open()) {
        if (cur_log_size_ > max_log_size_) {
            is << std::flush;

            std::ostringstream gz_file_name;
            gz_file_name << log_file_with_path_ << ".";
            gz_file_name << g3::localtime_formatted(g3::systemtime_now(), "%Y-%m-%d-%H-%M-%S");
            gz_file_name << ".gz";
            if (!createCompressedFile(log_file_with_path_, gz_file_name.str())) {
                fileWrite("Failed to compress log!");
                return false;
            }
            is.close();
            if (remove(log_file_with_path_.c_str()) == -1) {
                fileWrite("Failed to remove old log!");
            }
            changeLogFile(log_directory_);
            std::ostringstream ss;
            ss << "Log rotated Archived file name: " << gz_file_name.str().c_str();
            fileWrite(ss.str());
            ss.clear();
            ss.str("");
            ss << log_prefix_backup_ << ".log";
            expireArchives(log_directory_, ss.str(), max_archive_log_count_);

            return true;
        }
    }
    return false;
}

/**
 * Create a compressed file of the current log.
 * @param file_name
 * @param gzip_file_name
 * @return
 */
bool LogRotateHelper::createCompressedFile(std::string file_name, std::string gzip_file_name) {
    int buffer_size = 16184;
    char buffer[buffer_size];
    FILE* input = fopen(file_name.c_str(), "rb");
    gzFile output = gzopen(gzip_file_name.c_str(), "wb");

    if (input == NULL || output == NULL) {
        return false;
    }

    int N;
    while ((N = fread(buffer, 1, buffer_size, input)) > 0) {
        gzwrite(output, buffer, N);
    }
    if (gzclose(output) != Z_OK);
    if (fclose(input) != 0) {
        return false;
    }

    return true;
}

std::string LogRotateHelper::logFileName() {
    return log_file_with_path_;
}

void LogRotateHelper::addLogFileHeader() {
    filestream() << header();
}

```

These fixes resolved all performance issues.

**Comment by KjellKod** [comment] 2015-09-25 19:58
Thanks Robert!

Could you fork the repository and suggest these changes in a pull request?

**Comment by KjellKod** [comment] 2015-10-03 21:43
@rayrapetyan  please put up a pull request with these changes and I will review and test them.

**Comment by rayrapetyan** [comment] 2015-10-04 00:53
Sorry, I've lost track of this issue, committed all fixes.

**Comment by KjellKod** [comment] 2015-11-15 22:41
@rayrapetyan by skipping the flush there might be a huge build up of cached log entries. One other user told me that their logs only "flushed" every 10 minutes.

So I will add back the flush but making it configurable to flush every time or every X-time or never.
Does that sound good?

**Comment by rayrapetyan** [comment] 2015-11-16 04:20
Hm, I thought stream buffer size is defined by BUFSIZ (which is 1024 bytes by default) so what you said ("flushed" every 10 minutes) sounds really strange. There are few other layers below library (OS kernel, storage drivers etc), probably they are the real reason behind such a behavior and doing "flaush" more often would not help... 
Could this user share his compiler\OS version?

**Comment by KjellKod** [comment] 2015-11-16 05:39
I don't know the compiler but they used CentOS 6 and thought the kernel param 
vm.dirty_expire_centisecs Could be the cause.

Either way. I will make it configurable so people can choose whatever they want

**Comment by rayrapetyan** [comment] 2015-11-16 05:41
Sounds reasonable.

**Comment by KjellKod** [comment] 2015-11-24 06:07
closed in https://github.com/KjellKod/g3sinks/pull/17

**Closed by KjellKod** 2015-11-24 06:07 UTC
Labels: enhancement
